"""'make_flow_id_optional'

Revision ID: bdf7a79cd603
Revises: d546a2b0d862
Create Date: 2025-12-26 10:22:37.581353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = 'bdf7a79cd603'
down_revision: Union[str, None] = 'd546a2b0d862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_message', schema=None) as batch_op:
        batch_op.alter_column('flow_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_widget_message_flow_id'), ['flow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_widget_message_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('widget_session', schema=None) as batch_op:
        batch_op.alter_column('flow_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_session', schema=None) as batch_op:
        batch_op.alter_column('flow_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)

    with op.batch_alter_table('widget_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_widget_message_session_id'))
        batch_op.drop_index(batch_op.f('ix_widget_message_flow_id'))
        batch_op.alter_column('flow_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###
