"""'create_widget_tables'

Revision ID: d546a2b0d862
Revises: 5a37b7bf978e
Create Date: 2025-12-26 09:44:17.791044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd546a2b0d862'
down_revision: Union[str, None] = '5a37b7bf978e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_session',
    sa.Column('session_name', sa.Text(), nullable=True),
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_message',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('assistant_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['widget_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_history_id'))
        batch_op.drop_index(batch_op.f('ix_chat_history_session_id'))
        batch_op.drop_index(batch_op.f('ix_chat_history_user_id'))

    op.drop_table('chat_history')
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', sa.JSON(), nullable=True))
        batch_op.drop_column('metadata_json')

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_json', sqlite.JSON(), nullable=True))
        batch_op.drop_column('metadata')

    op.create_table('chat_history',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=True),
    sa.Column('session_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_message', sa.VARCHAR(), nullable=False),
    sa.Column('ai_reply', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_chat_history_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_history'))
    )
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_history_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_history_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_history_id'), ['id'], unique=False)

    op.drop_table('widget_message')
    op.drop_table('widget_session')
    # ### end Alembic commands ###
